const dummy=[
    {
        _id:1,
        src:"profile/avtar1.jpg"
    },
    {
        _id:2,
        src:"profile/avtar2.jpg"
    },
    {
        _id:3,
        src:"profile/avtar3.png"
    },
    {
        _id:4,
        src:"profile/avtar4.jpg"
    },
    {
        _id:5,
        src:"profile/avtar5.jpg"
    },
    {
        _id:6,
        src:"profile/avtar6.jpg"
    },
    {
        _id:7,
        src:"profile/avtar7.jpg"
    },
    {
        _id:8,
        src:"profile/avtar8.jpg"
    },
    {
        _id:9,
        src:"profile/avtar9.jpg"
    },
    {
        _id:10,
        src:"profile/avtar10.jpg"
    },
    {
        _id:11,
        src:"profile/avtar11.jpg"
    },
    {
        _id:12,
        src:"profile/avtar12.png"
    },
    {
        _id:13,
        src:"profile/avtar13.jpg"
    },
    {
        _id:14,
        src:"profile/avtar14.jpg"
    },
   
];

export default dummy;